name: 'Gradle Dependency Diff Report'
description: 'A GitHub Action that reports Gradle dependency differences.'
author: 'YUMEMI Inc.'
branding:
  icon: 'info'
  color: 'blue'
inputs:
  modules:
    description: 'Target Gradle modules separated by spaces.'
    required: true
  configuration:
    description: 'Configuration of Gradle dependencies task.'
    required: false
  project-dir:
    description: 'Root directory of the target application under the repository.'
    required: false
    default: '.'
  script:
    description: 'Bash script to run before Gradle dependencies task.'
    required: false
  report-title:
    description: 'Report title in job summary.'
    required: false
    default: 'Report from Gradle Dependency Diff Report action'
  head-ref:
    description: 'Current branch, tag, or commit SHA to compare with base.'
    required: false
    default: ${{ github.sha }}
  base-ref:
    description: 'Branch, tag, or commit SHA as a basis for comparison.'
    required: false
    default: |-
      ${{
        (github.event_name == 'pull_request' && github.base_ref) ||
        (github.event_name == 'push' && (startsWith(github.event.before, '0000') && github.event.repository.default_branch || github.event.before)) ||
        (github.event_name == 'merge_group' && github.event.merge_group.base_sha) ||
        github.event.repository.default_branch
      }}
  use-merge-base:
    description: 'Whether to compare with the latest common commit.'
    required: false
    default: 'false'
  repository: # opned for .github/workflows/ci.yml
    description: 'Target repository.'
    required: false
    default: ${{ github.repository }}
outputs:
  exists-diff:
    description: 'Whether there are any differences in dependencies.'
    value: ${{ steps.report.outputs.exists-diff }}
runs:
  using: 'composite'
  steps:
    - name: Report dependency differences
      id: report
      shell: bash
      env:
        MODULES: ${{ inputs.modules }}
        CONFIGURATION: ${{ inputs.configuration }}
        PROJECT_DIR: ${{ inputs.project-dir }}
        SCRIPT: ${{ inputs.script }}
        REPORT_TITLE: ${{ inputs.report-title }}
        HEAD_REF: ${{ inputs.head-ref }}
        BASE_REF: ${{ inputs.base-ref }}
        USE_MERGE_BASE: ${{ inputs.use-merge-base }}
        GH_REPO: ${{ inputs.repository }} # for GitHub CLI
        GH_TOKEN: ${{ github.token }} # for GitHub CLI
      run: |
        echo "::debug::git version: $(git --version)"
        echo "::debug::gh version: $(gh --version | tr '\n' ' ')"
        echo "::debug::jq version: $(jq --version)"
        source "$GITHUB_ACTION_PATH/raise_error.sh"
        source "$GITHUB_ACTION_PATH/create_file_name.sh"

        readonly WORK_DIR="$GITHUB_ACTION_PATH"

        if [ -z "$MODULES" ]; then raise_error "Specify 'modules' input."; fi

        mods=()
        confs=()

        for mod in $MODULES ; do
          conf="$CONFIGURATION"

          if [[ "$mod" =~ '|' ]]; then
            conf=${mod#*|}
            mod=${mod%%|*}
          fi

          if [[ -z "$mod" || -z "$conf" ]]; then raise_error "Incorrect 'modules' or 'configuration' input."; fi

          mods+=($mod)
          confs+=($conf)
        done

        # reuse in the same job
        if [ ! -d "$WORK_DIR/tools" ]; then
          mkdir "$WORK_DIR/tools"

          # get dependency-diff-tldr
          curl -f -L -o "$WORK_DIR/tools/dependency-diff-tldr-r8.jar" 'https://github.com/careem/dependency-diff-tldr/releases/download/v0.0.6/dependency-diff-tldr-r8.jar'
          if [ 'b76af4e71fe1bc3362207d648542337c21ab91e8' != "$(cat "$WORK_DIR/tools/dependency-diff-tldr-r8.jar" | openssl sha1 | awk '{print $2}')" ]; then
            raise_error "Incorrect checksum for dependency-diff-tldr-r8.jar."
          fi

          # get Dependency Tree Diff
          curl -f -L -o "$WORK_DIR/tools/dependency-tree-diff.jar" 'https://github.com/JakeWharton/dependency-tree-diff/releases/download/1.2.0/dependency-tree-diff.jar'
          if [ '949394274f37c06ac695b5d49860513e4d16e847' != "$(cat "$WORK_DIR/tools/dependency-tree-diff.jar" | openssl sha1 | awk '{print $2}')" ]; then
            raise_error "Incorrect checksum for dependency-tree-diff.jar."
          fi
        fi

        if [ ! -d "$WORK_DIR/deps" ]; then mkdir "$WORK_DIR/deps"; fi

        if [[ -z "$HEAD_REF" || -z "$BASE_REF" ]]; then raise_error "Specify 'head-ref' and 'base-ref' inputs."; fi

        if [ ! -d "$WORK_DIR/sources" ]; then
          gh repo clone "$GH_REPO" "$WORK_DIR/sources" -- --depth 1 --no-checkout > /dev/null 2>&1 || raise_error "May not have 'contents: read' permission."
          # ref: https://github.com/actions/checkout/blob/72f2cec99f417b1a1c5e2e88945068983b7965f9/src/git-auth-helper.ts#L55-L63
          cd "$WORK_DIR/sources" && git config --local 'http.https://github.com/.extraheader' "AUTHORIZATION: basic $(echo -n "x-access-token:$GH_TOKEN"|base64)"
        else
          cd "$WORK_DIR/sources"
        fi

        git fetch -q --depth 1 origin "$HEAD_REF" > /dev/null 2>&1 || raise_error "'head-ref' input is not valid."
        head_sha="$(git rev-parse FETCH_HEAD)"

        git fetch -q --depth 1 origin "$BASE_REF" > /dev/null 2>&1 || raise_error "'base-ref' input is not valid."
        base_sha="$(git rev-parse FETCH_HEAD)"

        if [ "$USE_MERGE_BASE" == 'true' ]; then
          merge_base_sha="$(gh api "repos/{owner}/{repo}/compare/${base_sha}...${head_sha}" | jq -r '.merge_base_commit.sha')"
          git fetch -q --depth 1 origin "$merge_base_sha"
          base_sha="$(git rev-parse FETCH_HEAD)"
        fi

        git checkout -q "$head_sha"
        eval "$SCRIPT"
        cd "$WORK_DIR/sources/$PROJECT_DIR"

        for i in "${!mods[@]}" ; do
          # on windows, files containing CR cause an error in diff tools
          ./gradlew -q ":${mods[$i]}:dependencies" --configuration "${confs[$i]}" | tr -d '\r' > "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$head_sha")"
        done

        cd "$WORK_DIR/sources"

        # cleanup
        git clean -df -q
        git checkout -q .

        git checkout -q "$base_sha"
        eval "$SCRIPT"
        cd "$WORK_DIR/sources/$PROJECT_DIR"

        for i in "${!mods[@]}" ; do
          # on windows, files containing CR cause an error in diff tools
          ./gradlew -q ":${mods[$i]}:dependencies" --configuration "${confs[$i]}" | tr -d '\r' > "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$base_sha")"
        done

        exists=false

        {
          echo "### $REPORT_TITLE"
          echo ''
          echo "- head ref: [${HEAD_REF}](https://github.com/${GH_REPO}/commit/${head_sha})"
          echo "- base ref: [${BASE_REF}](https://github.com/${GH_REPO}/commit/${base_sha})"

          for i in "${!mods[@]}" ; do
            result="$(java -jar "$WORK_DIR/tools/dependency-diff-tldr-r8.jar" \
              "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$base_sha")" "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$head_sha")")"

            echo ''

            if [ -n "$result" ]; then
              exists=true

              echo ":yellow_square: \`${mods[$i]}\` module (\`${confs[$i]}\` configuration)"
              echo ''
              echo '```'
              echo "$result"
              echo '```'

              result_detail="$(java -jar "$WORK_DIR/tools/dependency-tree-diff.jar" \
                "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$base_sha")" "$WORK_DIR/deps/$(create_file_name ":${mods[$i]}" "${confs[$i]}" "$head_sha")")"

              echo ''
              echo '<details>'
              echo '<summary>detail</summary>'
              echo ''
              echo '```diff'
              echo "$result_detail"
              echo '```'
              echo '</details>'
            else
              echo ":green_square: \`${mods[$i]}\` module (\`${confs[$i]}\` configuration)"
              echo ''
              echo 'No differences in dependencies, when this module is the base point.'
            fi
          done
        } >> "$GITHUB_STEP_SUMMARY"

        echo "exists-diff=$exists" >> "$GITHUB_OUTPUT"
